import 'song_model.dart';

class AiPlaylistPlan {
  final String playlistTitle;
  final String playlistDescription;
  final List<String> searchQueries;
  final List<String> preferredGenres;
  final List<String> preferredArtists;
  final List<String> avoidArtists;
  final List<String> vibeKeywords;
  final List<String> mustMatch;
  final List<String> mustNotMatch;
  final bool strictMode;
  final String energy;
  final int targetSize;

  const AiPlaylistPlan({
    required this.playlistTitle,
    required this.playlistDescription,
    required this.searchQueries,
    required this.preferredGenres,
    required this.preferredArtists,
    required this.avoidArtists,
    required this.vibeKeywords,
    required this.mustMatch,
    required this.mustNotMatch,
    required this.strictMode,
    required this.energy,
    required this.targetSize,
  });

  factory AiPlaylistPlan.fromJson(Map<String, dynamic> json) {
    return AiPlaylistPlan(
      playlistTitle: json['playlist_title'] as String? ?? 'AI Playlist',
      playlistDescription:
          json['playlist_description'] as String? ?? 'Generated by AI',
      searchQueries: _asStringList(json['search_queries']),
      preferredGenres: _asStringList(json['preferred_genres']),
      preferredArtists: _asStringList(json['preferred_artists']),
      avoidArtists: _asStringList(json['avoid_artists']),
      vibeKeywords: _asStringList(json['vibe_keywords']),
      mustMatch: _asStringList(json['must_match']),
      mustNotMatch: _asStringList(json['must_not_match']),
      strictMode: json['strict_mode'] == true,
      energy: json['energy'] as String? ?? 'medium',
      targetSize: (json['target_size'] as num?)?.toInt() ?? 12,
    );
  }

  static List<String> _asStringList(Object? value) {
    if (value is! List) return const [];
    return value
        .whereType<String>()
        .map((item) => item.trim())
        .where((item) => item.isNotEmpty)
        .toList();
  }
}

class AiGeneratedPlaylist {
  final String prompt;
  final AiPlaylistPlan plan;
  final List<SongModel> songs;

  const AiGeneratedPlaylist({
    required this.prompt,
    required this.plan,
    required this.songs,
  });

  String? get coverImage {
    for (final song in songs) {
      if (song.albumArt != null && song.albumArt!.isNotEmpty) {
        return song.albumArt;
      }
    }
    return null;
  }
}
